Avoid NoSuchMethodError of List.removeLast() on 24Q2
It's a temporary problem on 24Q2 before the new API lands on 24Q3.
In this CL, the callsite is fixed to avoid calling the API that doesn't
exist on 24Q2.

This CL tries to fix the problem caused between mainline and the new flag system.

Bug: 326109524
Test: m tracinglib-platform
Change-Id: I5e7c5b2d965fa37b844ae8df415f5597578323d0